name: Coupang Partners API 자동 실행

on:
  workflow_dispatch: # 깃허브에서 직접 'Run workflow' 버튼 눌러서 실행 가능
  schedule:
    # cron은 UTC 기준 시간. '0 0 * * *'은 UTC 자정(0시).
    # 한국 시간(KST)으로 변환하면 +9시간 -> 오전 9시에 실행됨!
    - cron: '0 0 * * *'

jobs:
  run-api-script:
    runs-on: ubuntu-latest # 이 코드를 리눅스 컴퓨터에서 돌려줘

    permissions:
      contents: write # 이 액션이 Git 저장소에 파일을 쓰고 커밋할 수 있도록 권한 부여

    steps:
    - name: 레포지토리 코드 가져오기
      uses: actions/checkout@v3 # 깃허브 레포지토리 파일을 가져와서 작업 환경 준비

    - name: Python 설치
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # 최신 Python 3 버전으로 설치해줘

    - name: 필요한 라이브러리 설치 (requests, Pillow - 이미지 처리용, 없으면 안 깔림)
      run: |
        python -m pip install --upgrade pip
        pip install requests Pillow # 혹시 이미지 처리하게 될까봐 Pillow도 같이 설치

    - name: 쿠팡 API 스크립트 실행 & HTML 파일 생성
      env: # 아까 Secrets에 저장한 쿠팡 키를 가져와서 코드에 넣어줘
        COUPANG_ACCESS_KEY: ${{ secrets.COUPANG_ACCESS_KEY }}
        COUPANG_SECRET_KEY: ${{ secrets.COUPANG_SECRET_KEY }}
      run: |
        python coupang_api.py # HTML 파일들이 현재 작업 환경에 생성될 거야

    - name: 생성된 HTML 파일들을 Git에 커밋하기
      # stefanzweifel/git-auto-commit-action 액션은 자동으로 변경된 파일을 감지해서 커밋하고 푸시해줌
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "feat: 쿠팡 파트너스 자동 생성 상품 페이지 추가" # 커밋 메시지
        # GITHUB_TOKEN은 깃허브에서 기본으로 제공하는 토큰이고, 위의 permissions: contents: write 권한으로 충분히 작동함.
        # token: ${{ secrets.GITHUB_TOKEN }} # (이 줄은 명시 안 해도 기본적으로 사용됨)
        # 생성된 파일들을 현재 디렉토리에만 생성하므로 별도 path 지정 필요 없음
