name: Coupang Partners API 자동 실행

on:
  workflow_dispatch: # 깃허브에서 직접 'Run workflow' 버튼 눌러서 실행 가능
  schedule:
    - cron: '0 0 * * *' # UTC 기준으로 매일 자정(새벽 9시)에 실행됨 (한국 시간)

jobs:
  run-api-script:
    runs-on: ubuntu-latest # 이 코드를 리눅스 컴퓨터에서 돌려줘

    steps:
    - name: 레포지토리 코드 가져오기
      uses: actions/checkout@v3

    - name: Python 설치
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # 최신 Python 3 버전으로 설치해줘

    - name: 필요한 라이브러리 설치 (requests)
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: 쿠팡 API 스크립트 실행
      env: # 아까 Secrets에 저장한 쿠팡 키를 가져와서 코드에 넣어줘
        COUPANG_ACCESS_KEY: ${{ c801a28c-0fe4-4c56-a582-30095af6c0ee }}
        COUPANG_SECRET_KEY: ${{ 201818d4435475d09a9c93d4d92486eb753b0df2 }}
      run: |
        python coupang_api.py
